apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blue
  labels:
    app: app-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-blue
  template:
    metadata:
      labels:
        app: app-blue
    spec:
      containers:
      - name: capstone-devops
        image: ajpm1977/capstone-devops:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  selector:
    app: app-blue
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
---
